openapi: "3.0.2"
info:
  title: Quotation API
  version: "1.0"
  contact:
    email: christina@omicron.at
  description: The API for Quotations
servers:
  - url: https://api.server.test/v1

paths:
  /rfqs:
    post:
      operationId: requestQuote
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Quotation"
      responses:
        "200":
          description: OK

components:
  schemas:
    Quotation:
      type: object
      properties:
        id:
          type: integer
          format: uuid
        product:
          type: string
          maxLength: 20
          pattern: '(\w+\W*)*'
        quantity:
          type: integer
          minimum: 0
          maximum: 1000
        price:
          type: number
          minimum: 0
        shipment:
          type: string
          enum:
            - FOB
            - DAT
        mode:
          type: string
          pattern: "[A-Z]{3}"
          maxLength: 3
